---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(plotly)
library(janitor)
library(ggthemes)
library(ggplot2)
library(gganimate)
library(tidyr)
library(readxl)
library(RColorBrewer)
library(scales)

surge_all <- read_excel("surge_dataset_v9r.xlsx") %>% 
  clean_names()


all_mdaps_x <- surge_all %>% 
  filter(mdap == "MDAP",
         anomalous == 0) %>% 
  select(c(year:agg_max_years))

all_mdaps_x$year <- as.integer(all_mdaps_x$year)
all_mdaps_x$adjusted_surge_rate_years <- as.numeric(all_mdaps_x$adjusted_surge_rate_years)
all_mdaps_x$adjusted_surge_rate_years <- round(all_mdaps_x$adjusted_surge_rate_years, digits = 2)

all_mdaps_x_nas <- all_mdaps_x %>% 
  drop_na(adjusted_surge_rate_years) 

```


```{r smooth}

smooth_plot <- ggplot(all_mdaps_x_nas, aes(x = adjusted_surge_rate_years, 
                            group = as_factor(year),
                            fill = as_factor(year))) +
  geom_density(alpha = 0.5, stat = "bin") + 
  scale_x_continuous(name = "Years to Replace Inventory", 
                     breaks = seq(0,50, 10), 
                     limits = (c(0,50))) +
  labs(y = "Number of Programs",
       title = "Time to Replace MDAPs at Adjusted Surge Rate",
       fill = "Year") +
  facet_wrap(~ year) +
  scale_color_manual(values = c("1999", "2008", "2020"),
                     labels = c("1999", "2008", "2020")) +
  theme_economist()

```


```{r ggplot}

ggplot(all_mdaps_x_nas, aes(x = adjusted_surge_rate_years, fill = as_factor(year))) +
  geom_histogram(alpha = 0.6, position = 'identity', binwidth = 1.2) +
  scale_x_continuous(breaks = seq(0,30, 5), 
                     limits = (c(0,30))) +
  labs(title = "Time to Replace MDAPs at Adjusted Surge Rate",
       fill = "Year",
       x = "Years to Replace Inventory",
       y = "Number of Programs") +
  theme_economist() +
  facet_wrap(~ year)


```


```{r plotly}

group_1999 <- all_mdaps_x_nas %>% 
  filter(year == 1999)

group_2008 <- all_mdaps_x_nas %>% 
  filter(year == 2008)

group_2020 <- all_mdaps_x_nas %>% 
  filter(year == 2020)


brittle <- plot_ly(alpha = 0.6) %>% 
  add_histogram(x = ~group_1999$adjusted_surge_rate_years,
                name = "1999") %>% 
  add_histogram(x = ~group_2008$adjusted_surge_rate_years,
                name = "2008") %>% 
  add_histogram(x = ~group_2020$adjusted_surge_rate_years,
                name = "2020") %>% 
  layout(barmode = "overlay",
         title = "Time to replace MDAPs at adjusted surge rate",
         xaxis = list(title = "Years to Replace Inventory",
                      zeroline = FALSE),
         yaxis = list(title = "Number of programs",
                      zeroline = FALSE))

```

```{r density}

density_plot <- ggplot(all_mdaps_x_nas, aes(x = adjusted_surge_rate_years,
                                            group = as_factor(year),
                                            fill = as_factor(year))) +
  geom_density(alpha = 0.5) +
  scale_x_continuous(name = "Years to Replace Inventory", 
                     breaks = seq(0,30, 5), 
                     limits = (c(0,30))) +
  theme(plot.title = element_text(hjust = .5)) + 
  labs(y = "Proportion of Programs",
       fill = "Year") +
  theme_economist()

density_plot


```



